Milestone4/weatherApp/src/controllers/UserController.java
/**
 * Class: UserController
 * Objective: Direct request to correct pages and methods
 * Detail: This class contains two method onSubmitRegsitration and OnSumbit login which is used to register and login user respectively and direct them to correct pages
 * Date: 9/30/2018
 * Reference: CST-235
 */
package controllers;

import java.io.IOException;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.interceptor.Interceptors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import beans.User;
import business.UserBusinessInterface;
import business.WeatherBusinessInterface;
import util.LoggingInterceptor;
import util.UserNotFoundException;

/**
 * User controller class for directing user to register, weather display, and login. Uses an injected logger.
 * @author Aaron and Sunjil
 *
 */
@ManagedBean
@ViewScoped
@Interceptors(LoggingInterceptor.class)
public class UserController {
	
	/** The interf. */
	@Inject
	UserBusinessInterface interf;
	
	/** The service. */
	@Inject
	WeatherBusinessInterface service;
	
	 /** The logger. */
 	Logger logger= LoggerFactory.getLogger(UserController.class);
	
	/**
	 * This method is called when users submit their information on RegistrationForm.xhtml. 
	 * It directs users to the LoginForm if the all the required fields are filled out.
	 *
	 * @return the string
	 * @throws IOException Signals that an I/O exception has occurred.
	 */
	public String onSubmitRegistration() throws IOException
	{
		// get the User Managed Bean
				FacesContext context = FacesContext.getCurrentInstance();
				User user = context.getApplication().evaluateExpressionGet(context, "#{user}", User.class);

				// forward to Login form along with the User Managed Bean
				FacesContext.getCurrentInstance().getExternalContext().getRequestMap().put("user", user);
				//Putting user filled out information from the form to the database through bussiness interface
				interf.register(user);
				logger.info("Registration success");
				return "LoginForm.xhtml";
	}
	
	/**
	 * This method is called when user submit login inforamtion using LoginForm.xhtml
	 * It directs user to the HomePage if the username and password matches with information on database
	 *
	 * @return the string
	 */
	public String onSubmitLogin()  {
		// get the User Managed Bean
		FacesContext context = FacesContext.getCurrentInstance();
		User user = context.getApplication().evaluateExpressionGet(context, "#{user}", User.class);
		// forward to HomePage form along with the User Managed Bean
		FacesContext.getCurrentInstance().getExternalContext().getRequestMap().put("user", user);
		
		try{
			interf.login(user);
		}
		catch(UserNotFoundException e)
		{
			String info="Could not find user";
			FacesContext.getCurrentInstance().getExternalContext().getRequestMap().put("info", info);
			return "LoginForm.xhtml";

		}
		return "HomePage.xhtml";
	}
	
	
	

	/**
	 * Method to get the user business interface.
	 *
	 * @author Aaron and Sunjil
	 * @return the interface
	 */
	public UserBusinessInterface getInterface() {
		return interf;
	}
	
	/**
	 * Method to get the weather business interface.
	 *
	 * @author Aaron and Sunjil
	 * @return the weather interface
	 */
	public WeatherBusinessInterface getWeatherInterface()
	{
		return service;
	}

}

Milestone4/weatherApp/WebContent/DataChart.xhtml
	<ui:composition template="/layouts/commonLayout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
	
	
		<ui:define name="title"> Chart Page</ui:define>
		<ui:define name="content">
					
	<div id="myDiv">
		
	</div>
	<h:outputScript target="body">
			
		var trace2 = {
			    x: [],
			    y: [],
			    mode: 'lines',
			    name: 'Humidity'
			};
		var trace3 = {
			    x: [],
			    y: [],
			    mode: 'lines',
			    name: 'TempMin'
			};
		    var trace4= {
			    x: [],
			    y: [],
			    mode: 'lines',
			    name: 'TempMax'
			};
			

var jsonData = $.ajax({
    url: "/weatherApp/rest/weather/getChartData",
    dataType: "json",
  }).done(function (results) {

    for(let result of results.data){
      trace2.x.push(result.dateAndTime);
      trace2.y.push(result.humidity);
      trace3.x.push(result.dateAndTime);
      trace3.y.push(result.minTemp);
      trace4.x.push(result.dateAndTime);
      trace4.y.push(result.maxTemp);
     
    }

    var data = [trace2, trace3, trace4 ];

    var layout = {};

    Plotly.newPlot('myDiv', data, layout);
  });
</h:outputScript>
		<a href="Index.xhtml">
			<button class="buttons">Logout</button>
		</a>
		</ui:define>
	</ui:composition>

Milestone4/weatherApp/WebContent/DataTable.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

<h:head></h:head>
<body>
	<h:dataTable value="#{userController.weatherInterface.weatherData}"
		var="weather" styleClass="order-table"
		headerClass="order-table-header"
		rowClasses="order-table-odd-row,order-table-even-row">
		<h:column>
			<f:facet name="header">Temperature</f:facet>
								#{weather.temperature}
						</h:column>
		<h:column>
			<f:facet name="header">Maximum Temperature</f:facet>
								#{weather.maxTemp}
						</h:column>
		<h:column>
			<f:facet name="header">Minimum Temperature</f:facet>
								#{weather.minTemp}
						</h:column>
		<h:column>
			<f:facet name="header">Humidity</f:facet>
								#{weather.humidity}
						</h:column>
		<h:column>
			<f:facet name="header">Date</f:facet>
								#{weather.dateAndTime}
						</h:column>


	</h:dataTable>

		<a href="Index.xhtml">
			<button style="background: grey; color: white; width: 80px; height: 40px;">Logout</button>
		</a>
</body>
</html>

Milestone4/weatherApp/WebContent/Error.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head>
<title>Common Exception Page</title>
</h:head> 
<h:body> 
	
	<!-- Set the layout and Title for this page -->
 		<ui:composition template="/layouts/commonLayout.xhtml">
		<ui:define name="title">Common Exception Page</ui:define>
		<ui:define name="content">
				<!-- Login Form -->
				
				<div align="center">
				
	<h3>Exception Message:</h3>
	#{requestScope['error-message']} <br/>
	<h:form>
			<h:button value="Index" outcome="Index.xhtml"/>
	</h:form>
	<h:messages />
	</div>
	</ui:define>
	</ui:composition>
</h:body>
</html>

Milestone4/weatherApp/WebContent/HomePage.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head>
<title>Login Page</title>
</h:head> 
<h:body> 
	
	<!-- Set the layout and Title for this page -->
 		<ui:composition template="/layouts/commonLayout.xhtml">
		<ui:define name="title">JSF Login Page</ui:define>
		<ui:define name="content">
				<!-- Login Form -->
				
				<div align="center">
	
	<h:form>
		<h:commandButton action="#{weatherController.onSubmitViewTable}" value="Table " />
		<br/><br/>
		<h:commandButton action="#{weatherController.onSubmitViewChart}" value="Chart " />
		<br/><br/>
		
		<h:button value="Index  " outcome="Index.xhtml"/>
	</h:form>
	<h:messages />
	</div>
	</ui:define>
	</ui:composition>
</h:body>
</html>

Milestone4/weatherApp/WebContent/Index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head>
<title>Index Page</title>
</h:head> 
<h:body> 
	
	<ui:composition template="/layouts/commonLayout.xhtml">
		<ui:define name="title">JSF Login Page</ui:define>
		<ui:define name="content">
				<!-- Login Form -->
				
				<div align="center">
	
	<h:form>
		<h:button class="buttons" value="Login" outcome="LoginForm.xhtml" /> <br/>
	</h:form>
	<br/>
	
	<h:form>
		<h:button class="buttons"  value="Register" outcome="RegistrationForm.xhtml"/>
	</h:form>
	</div>
	</ui:define>
	</ui:composition>
	</h:body>
</html>

Milestone4/weatherApp/WebContent/LoginForm.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head>
<title>Login Page</title>
</h:head> 
<h:body> 
	
	<!-- Set the layout and Title for this page -->
 		<ui:composition template="/layouts/commonLayout.xhtml">
		<ui:define name="title">JSF Login Page</ui:define>
		<ui:define name="content">
				<!-- Login Form -->
				
				<div align="center">
	
	<h:form>
	<!-- get username and password -->
		<p>Username: </p><h:inputText id="username" value="#{user.username}" title="" maxlength="20"/><br/><br/>
		<p>Password: </p><h:inputText id="password" value="#{user.password}" title="" maxlength="20"/> <br/>
		<br/>
		<h:commandButton class="buttons" action="#{userController.onSubmitLogin}" value="Submit" />
		<br/><br/>
		<h:button class="buttons" value="Go Home" outcome="Index.xhtml"/>
	</h:form>
	${info}
	<h:messages />
	</div>
	</ui:define>
	</ui:composition>
</h:body>
</html>

Milestone4/weatherApp/WebContent/RegistrationForm.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head>
<title>Login Page</title>
</h:head> 
<h:body> 
	<!-- Set the layout and Title for this page -->
 		<ui:composition template="/layouts/commonLayout.xhtml">
		<ui:define name="title">SJ Registration</ui:define>
		<ui:define name="content">
				<!-- Login Form -->
				
				<div align="center">
	<h:form>
	<!-- get all user attributes -->
		First Name: <h:inputText id="firstName" value="#{user.firstName}" title="" maxlength="20"/> <br/>
		Last Name : <h:inputText id="lastName" value="#{user.lastName}"   title="" maxlength="20"/> <br/>
		Username  : <h:inputText id="username" value="#{user.username}"   title="" maxlength="20"/> <br/>
		Password  : <h:inputText id="password" value="#{user.password}"   title="" maxlength="20"/> <br/>
		<h:commandButton class="buttons" action="#{userController.onSubmitRegistration}"  value="Submit" />
		<br/>
		<h:button class="buttons" value="Go Home" outcome="Index.xhtml"/>
	</h:form>
	<h:messages />
	</div>
	</ui:define>
	</ui:composition>
</h:body>
</html>